[package]
name = "soku"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/r0nsha/soku-rs"

[[bin]]
name = "soku"

[dependencies]
bit-set = "0.5.3"
derive_more = "0.99.17"
itertools = "0.10.5"
rand = "0.8.5"
thiserror = "1.0.38"
